// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apiproto/apipb.proto

package apiproto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Addrequest struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string               `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Fullname             string               `protobuf:"bytes,3,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Salary               int64                `protobuf:"varint,4,opt,name=salary,proto3" json:"salary,omitempty"`
	InsertAt             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=insert_at,json=insertAt,proto3" json:"insert_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Addrequest) Reset()         { *m = Addrequest{} }
func (m *Addrequest) String() string { return proto.CompactTextString(m) }
func (*Addrequest) ProtoMessage()    {}
func (*Addrequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1769b40471972737, []int{0}
}

func (m *Addrequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Addrequest.Unmarshal(m, b)
}
func (m *Addrequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Addrequest.Marshal(b, m, deterministic)
}
func (m *Addrequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Addrequest.Merge(m, src)
}
func (m *Addrequest) XXX_Size() int {
	return xxx_messageInfo_Addrequest.Size(m)
}
func (m *Addrequest) XXX_DiscardUnknown() {
	xxx_messageInfo_Addrequest.DiscardUnknown(m)
}

var xxx_messageInfo_Addrequest proto.InternalMessageInfo

func (m *Addrequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Addrequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Addrequest) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *Addrequest) GetSalary() int64 {
	if m != nil {
		return m.Salary
	}
	return 0
}

func (m *Addrequest) GetInsertAt() *timestamp.Timestamp {
	if m != nil {
		return m.InsertAt
	}
	return nil
}

type AddResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddResponse) Reset()         { *m = AddResponse{} }
func (m *AddResponse) String() string { return proto.CompactTextString(m) }
func (*AddResponse) ProtoMessage()    {}
func (*AddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1769b40471972737, []int{1}
}

func (m *AddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddResponse.Unmarshal(m, b)
}
func (m *AddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddResponse.Marshal(b, m, deterministic)
}
func (m *AddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddResponse.Merge(m, src)
}
func (m *AddResponse) XXX_Size() int {
	return xxx_messageInfo_AddResponse.Size(m)
}
func (m *AddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddResponse proto.InternalMessageInfo

func (m *AddResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Addrequest)(nil), "api.Addrequest")
	proto.RegisterType((*AddResponse)(nil), "api.AddResponse")
}

func init() { proto.RegisterFile("apiproto/apipb.proto", fileDescriptor_1769b40471972737) }

var fileDescriptor_1769b40471972737 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xc1, 0x4e, 0x84, 0x30,
	0x10, 0x86, 0x83, 0xec, 0xae, 0xec, 0x70, 0xd0, 0x34, 0xc6, 0x10, 0x2e, 0x92, 0x3d, 0x71, 0x2a,
	0xc9, 0x7a, 0xd8, 0x83, 0x27, 0x7c, 0x04, 0xd4, 0x8b, 0x17, 0x53, 0xb6, 0xb3, 0xa4, 0x09, 0xd0,
	0xda, 0x29, 0x1a, 0x1f, 0xcb, 0x37, 0x34, 0xd0, 0xad, 0x7b, 0xe2, 0xff, 0xe6, 0x1f, 0xd2, 0x2f,
	0x03, 0x77, 0xc2, 0x28, 0x63, 0xb5, 0xd3, 0xd5, 0x1c, 0x5a, 0xbe, 0x64, 0x16, 0x0b, 0xa3, 0xf2,
	0x87, 0x4e, 0xeb, 0xae, 0xc7, 0x6a, 0x19, 0xb5, 0xd3, 0xa9, 0x72, 0x6a, 0x40, 0x72, 0x62, 0x30,
	0x7e, 0x6b, 0xf7, 0x1b, 0x01, 0xd4, 0x52, 0x5a, 0xfc, 0x9c, 0x90, 0x1c, 0xcb, 0x21, 0x99, 0x08,
	0xed, 0x28, 0x06, 0xcc, 0xa2, 0x22, 0x2a, 0xb7, 0xcd, 0x3f, 0xcf, 0x9d, 0x11, 0x44, 0xdf, 0xda,
	0xca, 0xec, 0xca, 0x77, 0x81, 0xe7, 0xee, 0x34, 0xf5, 0xfd, 0xf2, 0x5f, 0xec, 0xbb, 0xc0, 0xec,
	0x1e, 0x36, 0x24, 0x7a, 0x61, 0x7f, 0xb2, 0x55, 0x11, 0x95, 0x71, 0x73, 0x26, 0x76, 0x80, 0xad,
	0x1a, 0x09, 0xad, 0xfb, 0x10, 0x2e, 0x5b, 0x17, 0x51, 0x99, 0xee, 0x73, 0xee, 0x7d, 0x79, 0xf0,
	0xe5, 0xaf, 0xc1, 0xb7, 0x49, 0xfc, 0x72, 0xed, 0x76, 0x4f, 0x90, 0xd6, 0x52, 0x36, 0x48, 0x46,
	0x8f, 0x84, 0x8c, 0xc1, 0xea, 0xa8, 0xa5, 0xf7, 0x5d, 0x37, 0x4b, 0x66, 0x19, 0x5c, 0x0f, 0x48,
	0x24, 0x3a, 0x3c, 0xab, 0x06, 0xdc, 0x1f, 0x20, 0x7d, 0x23, 0xb4, 0x2f, 0x68, 0xbf, 0xd4, 0x11,
	0x59, 0x09, 0x71, 0x2d, 0x25, 0xbb, 0xe1, 0xc2, 0x28, 0x7e, 0x39, 0x44, 0x7e, 0x1b, 0x06, 0xe1,
	0x99, 0x67, 0x78, 0x4f, 0xc2, 0x9d, 0xdb, 0xcd, 0xf2, 0x79, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff,
	0x7e, 0x5d, 0xdf, 0xe1, 0x7a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Add(ctx context.Context, in *Addrequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Add(ctx context.Context, in *Addrequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Add(context.Context, *Addrequest) (*AddResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Add(ctx context.Context, req *Addrequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Addrequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Add(ctx, req.(*Addrequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _UserService_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apiproto/apipb.proto",
}
